# Site settings
name: Kumar Kundan
email: kkajnabi.kumar@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, AngularJS, Angular2, React-Native, NodeJS, MongoDB, AWS, Machine Learning, Deep Learning, Startups, Agile, Pair Programming"
skills: "Software Developer from Bangalore, Karnataka (India)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/kumar-kundan-301377a2/
  - title: facebook
    url: https://www.facebook.com/kumar.kundan.54
  - title: twitter
    url: https://twitter.com/kkajnabi
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
